version: '2'

services:

  web:
    build:
      context: ./code
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "80:80"
    links:
      - web
    command: nginx -g "daemon off;"
